# Generated by Django 3.1.4 on 2020-12-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoLearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
